export const ATTRIBUTE_LABELS: Record<string, string> = {
  screenSize: 'Діагональ екрану',
  screenType: 'Тип екрану',
  storage: 'Накопичувач',
  camera: 'Камера',
  batteryCapacity: 'Ємність батареї',
  batteryLife: 'Час роботи батареї',
  processor: 'Процесор',
  ram: "Оперативна пам'ять",
  has5G: 'Підтримка 5G',
  refreshRate: 'Частота оновлення',
  gpu: 'Відеокарта',
  weight: 'Вага',
  type: 'Тип',
  wireless: 'Бездротовий',
  noiseCancelling: 'Шумозаглушення',
  microphone: 'Мікрофон',
  waterResistant: 'Водостійкість',
  driverSize: 'Розмір драйвера',
  impedance: 'Імпеданс',
  cellularSupport: 'Підтримка SIM',
  pencilSupport: 'Підтримка стилуса',
  keyboardSupport: 'Підтримка клавіатури',
  dpi: 'DPI',
  buttons: 'Кількість кнопок',
  sensor: 'Сенсор',
  rgb: 'RGB підсвічування',
  programmableButtons: 'Програмовані кнопки',
};
